name: BCNet
channels:
  - pytorch
  - defaults
dependencies:
  - blas=1.0=mkl
  - ca-certificates=2020.10.14
  - certifi=2020.6.20
  - cudatoolkit=10.2.89
  - freetype=2.10.4
  - intel-openmp=2020.2
  - jpeg=9b
  - libpng=1.6.37
  - libtiff=4.1.0
  - lz4-c=1.9.2
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.2.0
  - mkl_random=1.1.1
  - numpy=1.19.1
  - numpy-base=1.19.1
  - olefile=0.46
  - openssl=1.1.1h
  - pillow=8.0.0
  - pip=20.2.4
  - python=3.7.4
  - pytorch=1.6.0
  - setuptools=50.3.0
  - six=1.15.0
  - sqlite=3.33.0
  - tk=8.6.10
  - torchvision=0.7.0
  - wheel=0.35.1
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.5
  - pip:
    - ase==3.20.1
    - chardet==3.0.4
    - cycler==0.10.0
    - decorator==4.4.2
    - future==0.18.2
    - googledrivedownloader==0.4
    - h5py==2.10.0
    - idna==2.10
    - isodate==0.6.0
    - joblib==0.17.0
    - kiwisolver==1.2.0
    - llvmlite==0.34.0
    - matplotlib==3.3.2
    - networkx==2.5
    - numba==0.51.2
    - opencv-python==4.4.0.44
    - pandas==1.1.3
    - plyfile==0.7.2
    - pyparsing==2.4.7
    - python-dateutil==2.8.1
    - pytz==2020.1
    - rdflib==5.0.0
    - requests==2.24.0
    - scikit-learn==0.23.2
    - scipy==1.5.3
    - threadpoolctl==2.1.0
    - torch-cluster==1.5.7
    - torch-geometric==1.5.0
    - torch-scatter==2.0.5
    - torch-sparse==0.6.7
    - torch-spline-conv==1.2.0
    - tqdm==4.50.2
    - urllib3==1.25.11

